### ISSUE TITLE
/admin 에 들어가지지 않음.

### ISSUE THREAD

**Issue by hansolJu** [hansolJu/PaceMaker#3]
No module named 'dataParser.my_auth' 에러 발생.

**Comment by isk03276** [comment]
이거 내문젠데...이거

**Comment by isk03276** [comment]
admin 처음 시작하는거 안해서그런거아녜여????

**Comment by isk03276** [comment]
python manage.py createsuperuser로 하면됨

**Comment by blesk011** [comment]
abstractUser를 사용하고 커스텀 인증을 setting.py에서 제거 하였다. ---해결!!
